flags: {}
local-bin-path: __shake-build
packages:
- location: .
- location: ../haskell-flight-fsdb
  extra-dep: true
- location: ../haskell-flight-igc
  extra-dep: true
- location: ../haskell-flight-kml
  extra-dep: true
extra-deps:
- hxt-xpath-9.1.2.2
resolver: lts-8.13
